### ISSUE TITLE
Shouldn't Bond allow only a single Dynamic to be binded to it?

### ISSUE THREAD

**Issue by TadeasKriz** [SwiftBond/Bond#123] opened 2015-08-08 15:05 UTC
I was going through the code and as far as I can see, when I do this:
```
let bond = Bond<String>() { println($0) }
let dynamic1 = Dynamic<String>("hello")
let dynamic2 = Dynamic<String>("world")
dynamic1 ->> bond
dynamic2 ->> bond
dynamic1.value = "stranger"
```

I get output:
```
hello
world
stranger
```
Which is rather strange, because I would expect that only the last dynamic would be bound to the Bond, simply because there is the function `any([Dynamic<T>]) -> Dynamic<T>` which seems to be doing exactly that. If this is not intended behavior (which I would understand), then there is a bug in the example for TableView and CollectionView DataSource which does this:
```
repositories.map { [unowned self] (repository: Repository) -> RepositoryTableViewCell in
    let cell = self.tableView.dequeueReusableCellWithIdentifier("cell") as RepositoryTableViewCell
    repository.name ->> cell.nameLabel
    repository.photo ->> cell.avatarImageView
    return cell
  } ->> tableViewDataSourceBond
```

And from what I can tell, it will be rebinding the `repository.name` and `repository.photo` to the cell's fields multiple times and also, when I will scroll down and then change the value of the first `Repository` name `Dynamic`, it will get changed on one of the drawn cells, because iOS recycle them whenever possible. A workaround for that would be to call `cell.nameLabel.designatedBond.unbindAll()` and `cell.avatarImageView.designatedBond.unbindAll()` before binding it again.

So what is the intended behavior? Is it a bug in the code or in the readme? Thanks.

**Comment by ivanmoskalev** [comment] 2015-08-08 15:09
Good catch, I've encountered that just today. I think any Bond indeed shall be bound to only one Dynamic at a time.

**Comment by TadeasKriz** [comment] 2015-08-09 14:34
@srdanrasic What's your view on this?

**Comment by srdanrasic** [comment] 2015-08-10 08:41
The problem is that a Dynamic uses a Bond to make it bindable. If the Bond would accept only one connection, it would not allow updating the Dynamic from multiple sources where `any` is not feasible - a valid scenario.

Hopefully, Bond v4 deprecates Bond class in favor of a plain closure.

**Comment by TadeasKriz** [comment] 2015-08-10 08:46
@srdanrasic What is the difference between:
```
dynamic1 ->> dynamicX
dynamic2 ->> dynamicX
```
and
```
any(dynamic1, dynamic2) ->> dynamicX
```
Because I think that even the dynamic should not be allowed to have more than one other dynamic binded to it. What is the use case for it anyway?

**Comment by ivanmoskalev** [comment] 2015-08-10 09:08
I too think that allowing multiple sources is encouraging bad practices. If
we need this only internally, maybe it makes more sense to make a special
many-to-one Bond for internal use?

By the way, I can't wait to see Bond v.4 :) Have a feeling it would be
super awesome.

понедельник, 10 августа 2015 г. пользователь Tadeas Kriz написал:

**Comment by srdanrasic** [comment] 2015-08-30 14:17
Bonds are deprecated in v4. Closing.

**Closed by srdanrasic** 2015-08-30 14:17 UTC
